const { Prisma } = require("@prisma/client");

const schools = [
  {
    name: "Arcadia PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Barnier PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Baulkham Hills North PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Beaumont Hills PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Castle Hill PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Chittaway Bay PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Christ The King - North Rocks",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Ermington PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Galston PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "German International School Sydney",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Glenhaven PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Glenorie PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    //NOTE: Gordon West does not appear to do group tuition. All students must be enrolled in private tuition, arranged by parents and not organised through TSA
    name: "Gordon West PS",
    costGroup: 0,
    costPrivate: 0,
    costBandOnly: 125,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Holy Family Lindfield",
    costGroup: 240,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Ironbark Ridge PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "John Palmer PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "John Purchase PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Kanwal PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Kellyville Ridge PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Kenthurst PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Melrose Park PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Muirfield High School",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Murray Farm PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Niagara Park PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "North Kellyville PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "North Rocks PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Northmead CAPA High School",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Our Lady Help of Christians",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 15,
    enrolFee: 30,
  },
  {
    name: "Our Lady of Dolours - Chatswood",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 20,
    enrolFee: 30,
  },
  {
    name: "Our lady Queen of Peace - Greystanes",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Our Lady of Lourdes - Baulkham Hills",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Our Lady of the Angels - Rouse Hill",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Our Lady of The Rosary - Kellyville",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Our Lady of The Rosary - Waitara",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 15,
    enrolFee: 30,
  },
  {
    name: "Ourimbah PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Parramatta East PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 10,
    enrolFee: 30,
  },
  {
    name: "Regentville PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Rouse Hill PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Russel Lea PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Sacred Heart - Pymble",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 35,
    enrolFee: 30,
  },
  {
    name: "Sherwood Ridge PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Smalls Road PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Agatha's - Pennant Hills",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 30,
    enrolFee: 30,
  },
  {
    name: "St Angela's - Castle Hill",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Anthony's - Marsfield",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Bernadette's - Castle Hill",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Bernard's - Berowra Heights",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 30,
    enrolFee: 30,
  },
  {
    name: "St Declan's - Penshurst",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 10,
    enrolFee: 30,
  },
  {
    name: "St Gerard's - Carlingford",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 35,
    enrolFee: 30,
  },
  {
    name: "St Kevin's - Eastwood",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Madeline's - Kenthurst",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Mary's - Rydalmere",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Michael's - Baulkham Hills",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Patrick's - Kogarah",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "St Philip Neri - Northbridge",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 15,
    enrolFee: 30,
  },
  {
    name: "Terrigal High School",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Terrigal PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    // NOTE: Similar to Gordon West this is a band rehearsal only school. The problem is they have a two tiered payment system with a training band charge of $125 and a concert band charge of $175 per term...
    // TODO you might have to extend your table to have a bandOnlyProgram? boolean
    name: "Waitara PS",
    costGroup: 0,
    costPrivate: 0,
    costBandOnly: 125,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Wamberal PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "West Ryde PS",
    costGroup: 250,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    // TODO: It doesn't look like Westmead PS offers private or bandonly tuition.
    name: "Westmead PS",
    costGroup: 220,
    costPrivate: 0,
    costBandOnly: 0,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "Woodport PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
  {
    name: "York PS",
    costGroup: 220,
    costPrivate: 500,
    costBandOnly: 110,
    resourceLevy: 10,
    facilityHire: 0,
    enrolFee: 30,
  },
];

const accessories = [
  {
    name: "Hats",
    description: "Things you can wear on your head",
  },
  {
    name: "Socks",
    description: "Things you can wear on your feet",
  },
  {
    name: "Shirts",
    description: "Things you wear on the top half of your body",
  },
];

const instruments = [
  {
    name: "Cool helmet.",
    description: "A nice helmet to wear on your head",
    price: new Prisma.Decimal(19.95),
    image: "/images/helmet.jpg",
    accessory_id: 1,
  },
  {
    name: "Grey T-Shirt",
    description: "A nice shirt that you can wear on your body",
    price: new Prisma.Decimal(22.95),
    image: "/images/shirt.jpg",
    category_id: 3,
  },
  {
    name: "Socks",
    description: "Cool socks that you can wear on your feet",
    price: new Prisma.Decimal(12.95),
    image: "/images/socks.jpg",
    category_id: 2,
  },
  {
    name: "Sweatshirt",
    description: "Cool sweatshirt that you can wear on your body",
    price: new Prisma.Decimal(12.95),
    image: "/images/sweatshirt.jpg",
    category_id: 3,
  },
];

// const categories = [
//   {
//     name: "Hats",
//     description: "Things you can wear on your head",
//   },
//   {
//     name: "Socks",
//     description: "Things you can wear on your feet",
//   },
//   {
//     name: "Shirts",
//     description: "Things you wear on the top half of your body",
//   },
// ];

// const products = [
//   {
//     name: "Cool helmet.",
//     description: "A nice helmet to wear on your head",
//     price: new Prisma.Decimal(19.95),
//     image: "/images/helmet.jpg",
//     category_id: 1,
//   },
//   {
//     name: "Grey T-Shirt",
//     description: "A nice shirt that you can wear on your body",
//     price: new Prisma.Decimal(22.95),
//     image: "/images/shirt.jpg",
//     category_id: 3,
//   },
//   {
//     name: "Socks",
//     description: "Cool socks that you can wear on your feet",
//     price: new Prisma.Decimal(12.95),
//     image: "/images/socks.jpg",
//     category_id: 2,
//   },
//   {
//     name: "Sweatshirt",
//     description: "Cool sweatshirt that you can wear on your body",
//     price: new Prisma.Decimal(12.95),
//     image: "/images/sweatshirt.jpg",
//     category_id: 3,
//   },
// ];

module.exports = {
  products,
  categories,
};
